### ISSUE TITLE
The training dataset is correct?

### ISSUE THREAD

**Issue by HIDDERINDARK** [zhiqic/ChartReader#11]
![image](https://github.com/zhiqic/ChartReader/assets/78258262/9f071792-4255-4a85-81e6-ff929f706f33)

I have a question about the KPDetection and the KPGrouping. Do they use the same dataset to train? Why is the argument `data_dir` different? The training dataset is only one. But there are a lot of errors erupt coming out while I am training the KPGrouping. More then that, the result of the KPDetection is not well.

![0ad60cfd61cfc4022fd992f2bd3b57a](https://github.com/zhiqic/ChartReader/assets/78258262/4c94d0f9-ca00-4d65-9454-b19de527a387)
The top picture is the KPDetection result using the default config from json file `KPDetection.json` which is in the `config` directory.

**Comment by HIDDERINDARK** [comment]
nohup: 忽略输入
wandb: Currently logged in as: aoeyuu-con (esheeper). Use `wandb login --relogin` to force relogin
wandb: - Waiting for wandb.init()...
wandb: \ Waiting for wandb.init()...
wandb: wandb version 0.16.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.4
wandb: Run data is saved locally in /home/dmind/workspace/ChartReader/ChartReader/wandb/run-20240304_114850-d3gmyn77
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run bar only
wandb: Network error (TransientError), entering retry loop.

  0%|          | 0/100000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (87) to match target batch_size (64).

  0%|          | 1/100000 [00:04<122:40:59,  4.42s/it]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (88) to match target batch_size (52).

  0%|          | 2/100000 [00:04<53:39:36,  1.93s/it] Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (828) to match target batch_size (60).

  0%|          | 3/100000 [00:04<31:42:12,  1.14s/it]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (112) to match target batch_size (48).

  0%|          | 4/100000 [00:04<21:15:02,  1.31it/s]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (1536) to match target batch_size (768).

  0%|          | 5/100000 [00:05<15:32:47,  1.79it/s]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (1255) to match target batch_size (231).

  0%|          | 6/100000 [00:05<12:07:42,  2.29it/s]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (1536) to match target batch_size (768).

  0%|          | 7/100000 [00:05<10:01:52,  2.77it/s]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (250) to match target batch_size (64).

  0%|          | 8/100000 [00:05<8:40:40,  3.20it/s] Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (337) to match target batch_size (13).

  0%|          | 9/100000 [00:05<7:36:12,  3.65it/s]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (832) to match target batch_size (64).

  0%|          | 10/100000 [00:06<7:06:05,  3.91it/s]Traceback (most recent call last):
  File "/home/dmind/workspace/ChartReader/ChartReader/train_extraction.py", line 144, in train
    training_loss = nnet.train_step(*training_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 50, in train_step
    loss = self(xs, ys)
           ^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/model_factory.py", line 44, in forward
    loss = self.loss_function(preds, ys, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/workspace/ChartReader/ChartReader/models/py_utils/kp.py", line 623, in forward
    group_loss += self.group_loss(group_preds[b_ind], group_targets_trim[b_ind])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/modules/loss.py", line 1174, in forward
    return F.cross_entropy(input, target, weight=self.weight,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dmind/.conda/envs/chart_reader/lib/python3.11/site-packages/torch/nn/functional.py", line 3029, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected input batch_size (232) to match target batch_size (36).

  0%|          | 10/100000 [00:07<20:33:31,  1.35it/s]
wandb: Waiting for W&B process to finish... (success).
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (TransientError), entering retry loop.

**Comment by yushenglong1** [comment]
哥，我问个问题，detection和group的数据集是怎么来的？是根据EC400K数据集处理来的吗？

**Comment by Kaonashi2486** [comment]
> 哥，我问个问题，detection和group的数据集是怎么来的？是根据EC400K数据集处理来的吗？

Hi,where did you guys get the dataset from?

**Comment by Kozavochka** [comment]
Did you train on the dataset from the Readme? Did it produce any results?
