### ISSUE TITLE
Category Index error? 

### ISSUE THREAD

**Issue by yanchuqiao** [zhiqic/ChartReader#12]
I passed the training data set, it raises index error. The categories_id in dataset and code are not matched. Can you please specify clearer the id numbers? I got index errors and try to fix it according to the training dataset, which doesn't work and made things way more complicated. 
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 6 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 5 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 6 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 4 is out of bounds for axis 1 with size 3
  0%|                                                                                                                     | 4/50000 [00:00<27:28, 30.34it/s]Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 6 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 5 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 4 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 5 is out of bounds for axis 1 with size 3
  0%|                                                                                                                     | 8/50000 [00:00<26:41, 31.21it/s]Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 4 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 6 is out of bounds for axis 1 with size 3
Shuffling...
Data extraction error occurred.
Traceback (most recent call last):
  File "/home/ubuntu/ChartReader/train_extraction.py", line 127, in train
    training, ind = sample_data(training_db, ind)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/ChartReader/sampling_function.py", line 528, in sample_data
    center_heatmaps[b_ind, category, yce, xce] = 1
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 4 is out of bounds for axis 1 with size 3
Too many extraction errors. Terminating...
  0%|

**Comment by HIDDERINDARK** [comment]
Yes, you need fix the code by yourself  T_T.
I have code this project for a month. But the final result is not good!

**Comment by HIDDERINDARK** [comment]
Yes, you need debug it by yourself. ^_^
I have test this code for a month. And the result is not good ~_~.

**Comment by LjZqqqq** [comment]
> Yes, you need debug it by yourself ^_^ I have test this code for a month. And the result is not good ~_~

How did you debug this part? Could you plz share some of your experience?

**Comment by yushenglong1** [comment]
> > 是的，你需要自己调试^_^ 这个代码我已经测试了一个月了。而且结果并不好~_~
> 
> 这部分是怎么调试的？您能分享一些您的经验吗？

加我QQ2447270260，交流一下，做毕设做头晕了

**Comment by Kozavochka** [comment]
Are you solve problem?
